BankAccount.create(balance: 10000, min_balance_enforced: true, min_balance: 1000)
BankAccount.create(balance: 5000, min_balance_enforced: false, min_balance: nil)
BankAccount.create(balance: 25000, min_balance_enforced: true, min_balance: 2000)
BankAccount.create(balance: 15000, min_balance_enforced: true, min_balance: 1000)
BankAccount.create(balance: 12000, min_balance_enforced: false, min_balance: nil)
